// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: accore/pb/phone.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid    string `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone  string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Phone) Reset() {
	*x = Phone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accore_pb_phone_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_accore_pb_phone_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_accore_pb_phone_proto_rawDescGZIP(), []int{0}
}

func (x *Phone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Phone) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Phone) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Phone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Phones struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phones []*Phone `protobuf:"bytes,1,rep,name=phones,proto3" json:"phones,omitempty"`
}

func (x *Phones) Reset() {
	*x = Phones{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accore_pb_phone_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Phones) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phones) ProtoMessage() {}

func (x *Phones) ProtoReflect() protoreflect.Message {
	mi := &file_accore_pb_phone_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phones.ProtoReflect.Descriptor instead.
func (*Phones) Descriptor() ([]byte, []int) {
	return file_accore_pb_phone_proto_rawDescGZIP(), []int{1}
}

func (x *Phones) GetPhones() []*Phone {
	if x != nil {
		return x.Phones
	}
	return nil
}

var File_accore_pb_phone_proto protoreflect.FileDescriptor

var file_accore_pb_phone_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x70, 0x62, 0x22, 0x57, 0x0a, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x32, 0x0a, 0x06, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x06, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6f,
	0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x63, 0x63, 0x6f,
	0x72, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accore_pb_phone_proto_rawDescOnce sync.Once
	file_accore_pb_phone_proto_rawDescData = file_accore_pb_phone_proto_rawDesc
)

func file_accore_pb_phone_proto_rawDescGZIP() []byte {
	file_accore_pb_phone_proto_rawDescOnce.Do(func() {
		file_accore_pb_phone_proto_rawDescData = protoimpl.X.CompressGZIP(file_accore_pb_phone_proto_rawDescData)
	})
	return file_accore_pb_phone_proto_rawDescData
}

var file_accore_pb_phone_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_accore_pb_phone_proto_goTypes = []interface{}{
	(*Phone)(nil),  // 0: accore.pb.Phone
	(*Phones)(nil), // 1: accore.pb.Phones
}
var file_accore_pb_phone_proto_depIdxs = []int32{
	0, // 0: accore.pb.Phones.phones:type_name -> accore.pb.Phone
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accore_pb_phone_proto_init() }
func file_accore_pb_phone_proto_init() {
	if File_accore_pb_phone_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accore_pb_phone_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accore_pb_phone_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Phones); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accore_pb_phone_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accore_pb_phone_proto_goTypes,
		DependencyIndexes: file_accore_pb_phone_proto_depIdxs,
		MessageInfos:      file_accore_pb_phone_proto_msgTypes,
	}.Build()
	File_accore_pb_phone_proto = out.File
	file_accore_pb_phone_proto_rawDesc = nil
	file_accore_pb_phone_proto_goTypes = nil
	file_accore_pb_phone_proto_depIdxs = nil
}
